version: '3'

services:
  etcd:
    image: quay.io/coreos/etcd:latest
    container_name: etcd
    ports:
      - "2379:2379"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"

  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - etcd
      - redis
      - mysql
