// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: proto/noticepb/notice.proto

package noticepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NoticeClient is the client API for Notice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoticeClient interface {
	GetSingleAdvice(ctx context.Context, in *GetSingleAdviceReq, opts ...grpc.CallOption) (*GetSingleAdviceResp, error)
	GetProjectAdvice(ctx context.Context, in *GetProjectAdviceReq, opts ...grpc.CallOption) (*GetProjectAdviceResp, error)
}

type noticeClient struct {
	cc grpc.ClientConnInterface
}

func NewNoticeClient(cc grpc.ClientConnInterface) NoticeClient {
	return &noticeClient{cc}
}

func (c *noticeClient) GetSingleAdvice(ctx context.Context, in *GetSingleAdviceReq, opts ...grpc.CallOption) (*GetSingleAdviceResp, error) {
	out := new(GetSingleAdviceResp)
	err := c.cc.Invoke(ctx, "/noticepb.Notice/GetSingleAdvice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeClient) GetProjectAdvice(ctx context.Context, in *GetProjectAdviceReq, opts ...grpc.CallOption) (*GetProjectAdviceResp, error) {
	out := new(GetProjectAdviceResp)
	err := c.cc.Invoke(ctx, "/noticepb.Notice/GetProjectAdvice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoticeServer is the server API for Notice service.
// All implementations must embed UnimplementedNoticeServer
// for forward compatibility
type NoticeServer interface {
	GetSingleAdvice(context.Context, *GetSingleAdviceReq) (*GetSingleAdviceResp, error)
	GetProjectAdvice(context.Context, *GetProjectAdviceReq) (*GetProjectAdviceResp, error)
	mustEmbedUnimplementedNoticeServer()
}

// UnimplementedNoticeServer must be embedded to have forward compatible implementations.
type UnimplementedNoticeServer struct {
}

func (UnimplementedNoticeServer) GetSingleAdvice(context.Context, *GetSingleAdviceReq) (*GetSingleAdviceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingleAdvice not implemented")
}
func (UnimplementedNoticeServer) GetProjectAdvice(context.Context, *GetProjectAdviceReq) (*GetProjectAdviceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectAdvice not implemented")
}
func (UnimplementedNoticeServer) mustEmbedUnimplementedNoticeServer() {}

// UnsafeNoticeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoticeServer will
// result in compilation errors.
type UnsafeNoticeServer interface {
	mustEmbedUnimplementedNoticeServer()
}

func RegisterNoticeServer(s grpc.ServiceRegistrar, srv NoticeServer) {
	s.RegisterService(&Notice_ServiceDesc, srv)
}

func _Notice_GetSingleAdvice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSingleAdviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServer).GetSingleAdvice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noticepb.Notice/GetSingleAdvice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServer).GetSingleAdvice(ctx, req.(*GetSingleAdviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notice_GetProjectAdvice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectAdviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServer).GetProjectAdvice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noticepb.Notice/GetProjectAdvice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServer).GetProjectAdvice(ctx, req.(*GetProjectAdviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Notice_ServiceDesc is the grpc.ServiceDesc for Notice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "noticepb.Notice",
	HandlerType: (*NoticeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSingleAdvice",
			Handler:    _Notice_GetSingleAdvice_Handler,
		},
		{
			MethodName: "GetProjectAdvice",
			Handler:    _Notice_GetProjectAdvice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/noticepb/notice.proto",
}
