// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: proto/noticepb/notice.proto

package noticepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Advice 结构体
type Advice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IssueId     int32  `protobuf:"varint,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	ProjectName string `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Advice      string `protobuf:"bytes,4,opt,name=advice,proto3" json:"advice,omitempty"`
}

func (x *Advice) Reset() {
	*x = Advice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_noticepb_notice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Advice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advice) ProtoMessage() {}

func (x *Advice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_noticepb_notice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advice.ProtoReflect.Descriptor instead.
func (*Advice) Descriptor() ([]byte, []int) {
	return file_proto_noticepb_notice_proto_rawDescGZIP(), []int{0}
}

func (x *Advice) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Advice) GetIssueId() int32 {
	if x != nil {
		return x.IssueId
	}
	return 0
}

func (x *Advice) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *Advice) GetAdvice() string {
	if x != nil {
		return x.Advice
	}
	return ""
}

type GetSingleAdviceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	AdviceId int32  `protobuf:"varint,3,opt,name=advice_id,json=adviceId,proto3" json:"advice_id,omitempty"`
}

func (x *GetSingleAdviceReq) Reset() {
	*x = GetSingleAdviceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_noticepb_notice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleAdviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleAdviceReq) ProtoMessage() {}

func (x *GetSingleAdviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_noticepb_notice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleAdviceReq.ProtoReflect.Descriptor instead.
func (*GetSingleAdviceReq) Descriptor() ([]byte, []int) {
	return file_proto_noticepb_notice_proto_rawDescGZIP(), []int{1}
}

func (x *GetSingleAdviceReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetSingleAdviceReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetSingleAdviceReq) GetAdviceId() int32 {
	if x != nil {
		return x.AdviceId
	}
	return 0
}

type GetSingleAdviceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *Advice `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetSingleAdviceResp) Reset() {
	*x = GetSingleAdviceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_noticepb_notice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleAdviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleAdviceResp) ProtoMessage() {}

func (x *GetSingleAdviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_noticepb_notice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleAdviceResp.ProtoReflect.Descriptor instead.
func (*GetSingleAdviceResp) Descriptor() ([]byte, []int) {
	return file_proto_noticepb_notice_proto_rawDescGZIP(), []int{2}
}

func (x *GetSingleAdviceResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSingleAdviceResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSingleAdviceResp) GetData() *Advice {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetProjectAdviceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username    string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token       string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ProjectName string `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
}

func (x *GetProjectAdviceReq) Reset() {
	*x = GetProjectAdviceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_noticepb_notice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProjectAdviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectAdviceReq) ProtoMessage() {}

func (x *GetProjectAdviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_noticepb_notice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectAdviceReq.ProtoReflect.Descriptor instead.
func (*GetProjectAdviceReq) Descriptor() ([]byte, []int) {
	return file_proto_noticepb_notice_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectAdviceReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetProjectAdviceReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetProjectAdviceReq) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

type GetProjectAdviceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*Advice `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetProjectAdviceResp) Reset() {
	*x = GetProjectAdviceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_noticepb_notice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProjectAdviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectAdviceResp) ProtoMessage() {}

func (x *GetProjectAdviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_noticepb_notice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectAdviceResp.ProtoReflect.Descriptor instead.
func (*GetProjectAdviceResp) Descriptor() ([]byte, []int) {
	return file_proto_noticepb_notice_proto_rawDescGZIP(), []int{4}
}

func (x *GetProjectAdviceResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetProjectAdviceResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetProjectAdviceResp) GetData() []*Advice {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_noticepb_notice_proto protoreflect.FileDescriptor

var file_proto_noticepb_notice_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x70, 0x62,
	0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e,
	0x6f, 0x74, 0x69, 0x63, 0x65, 0x70, 0x62, 0x22, 0x6e, 0x0a, 0x06, 0x41, 0x64, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x73, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x64, 0x76, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x64, 0x76, 0x69, 0x63, 0x65, 0x22, 0x63, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x64, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x61, 0x64, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x69, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x6a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65,
	0x70, 0x62, 0x2e, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32,
	0xaf, 0x01, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x2e,
	0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x6e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x1d, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x1e, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x74,
	0x69, 0x63, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_noticepb_notice_proto_rawDescOnce sync.Once
	file_proto_noticepb_notice_proto_rawDescData = file_proto_noticepb_notice_proto_rawDesc
)

func file_proto_noticepb_notice_proto_rawDescGZIP() []byte {
	file_proto_noticepb_notice_proto_rawDescOnce.Do(func() {
		file_proto_noticepb_notice_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_noticepb_notice_proto_rawDescData)
	})
	return file_proto_noticepb_notice_proto_rawDescData
}

var file_proto_noticepb_notice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_noticepb_notice_proto_goTypes = []interface{}{
	(*Advice)(nil),               // 0: noticepb.Advice
	(*GetSingleAdviceReq)(nil),   // 1: noticepb.GetSingleAdviceReq
	(*GetSingleAdviceResp)(nil),  // 2: noticepb.GetSingleAdviceResp
	(*GetProjectAdviceReq)(nil),  // 3: noticepb.GetProjectAdviceReq
	(*GetProjectAdviceResp)(nil), // 4: noticepb.GetProjectAdviceResp
}
var file_proto_noticepb_notice_proto_depIdxs = []int32{
	0, // 0: noticepb.GetSingleAdviceResp.data:type_name -> noticepb.Advice
	0, // 1: noticepb.GetProjectAdviceResp.data:type_name -> noticepb.Advice
	1, // 2: noticepb.Notice.GetSingleAdvice:input_type -> noticepb.GetSingleAdviceReq
	3, // 3: noticepb.Notice.GetProjectAdvice:input_type -> noticepb.GetProjectAdviceReq
	2, // 4: noticepb.Notice.GetSingleAdvice:output_type -> noticepb.GetSingleAdviceResp
	4, // 5: noticepb.Notice.GetProjectAdvice:output_type -> noticepb.GetProjectAdviceResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_noticepb_notice_proto_init() }
func file_proto_noticepb_notice_proto_init() {
	if File_proto_noticepb_notice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_noticepb_notice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Advice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_noticepb_notice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleAdviceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_noticepb_notice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleAdviceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_noticepb_notice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProjectAdviceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_noticepb_notice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProjectAdviceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_noticepb_notice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_noticepb_notice_proto_goTypes,
		DependencyIndexes: file_proto_noticepb_notice_proto_depIdxs,
		MessageInfos:      file_proto_noticepb_notice_proto_msgTypes,
	}.Build()
	File_proto_noticepb_notice_proto = out.File
	file_proto_noticepb_notice_proto_rawDesc = nil
	file_proto_noticepb_notice_proto_goTypes = nil
	file_proto_noticepb_notice_proto_depIdxs = nil
}
